################~~~~ SBA Auth ~~~~~##################
# - Deployment
# - ClusterIP
# - Node Port

## BASH BUILD Dockerfile
## -t tagname, -f file/reference, ./buildContext  
# docker build -t mansanhhub/srvc-auth -f Projects/SBA.Auth/Dockerfile .
# docker push mansanhhub/srvc-auth
# docker pull mansanhhub/srvc-auth

#---------------------------------------------# 
## BASH RUN Deployment srvc-auth
# kubectl apply -f ./__/K8S/DEV/C_SRVC/depl-auth.yaml -n sba-dev
# kubectl get pods -n sba-dev
# kubectl get deployments -n sba-dev
# kubectl logs -l app=srvc-auth --all-containers=true -n sba-dev
# kubectl rollout restart deployments depl-auth -n sba-dev

## BASH DELETE (Deployments & Service)
# kubectl scale deployment depl-auth --replicas=0 -n sba-dev
# kubectl delete -f ./__/K8S/DEV/C_SRVC/depl-auth.yaml -n sba-dev
# kubectl delete deployments depl-auth -n sba-dev
# kubectl delete services srvc-cip-auth -n sba-dev
#---------------------------------------------# 
#### (1) API Deployment (Auth) 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srvc-auth
  template:
    metadata:
      labels:
        app: srvc-auth
    spec:
      enableServiceLinks: false   # ✅ disables auto-injected env vars
      containers:
        - name: srvc-auth
          image: mansanhhub/srvc-auth
          imagePullPolicy: Always
          ports:
            - containerPort: 1104   # optional http
          env:
            - name: DOTNET_ENVIRONMENT
              value: K8S
            - name: Kestrel__Endpoints__Http__Url
              value: "http://+:1104"
            - name: Kestrel__Endpoints__Http__Protocols
              value: "Http1"
            - name: Kestrel__Endpoints__Https__Url
              value: "https://+:1105"
            - name: Kestrel__Endpoints__Https__Protocols
              value: "Http2"
            - name: Kestrel__Endpoints__Https__Certificate__Path
              value: "certs/dev-cert.pfx"
            - name: Kestrel__Endpoints__Https__Certificate__Password
              value: "yourpassword"
              
            - name: ConnectionStrings__Redis
              value: "srvc-cip-redis:6379,password=P@55w0rd!123"
            - name: ConnectionStrings__SqlConnection
              value: "Server=srvc-cip-mssql.sba-dev.svc.cluster.local,1433;Initial Catalog=SBA_Auth;User ID=sa;Password=P@55w0rd!123;TrustServerCertificate=true;"
              # value: "Server=srvc-cip-mssql.default.svc.cluster.local,1433;Initial Catalog=SBA_Auth;User ID=sa;Password=P@55w0rd!123;TrustServerCertificate=true;" # When no Namespace
            
            - name: Clients__Http_Host__Gateway
              value: http://srvc-cip-gateway:1100
            - name: Clients__Http_Host__Job
              value: http://srvc-cip-job:1102
            - name: Clients__Http_Host__Auth
              value: http://srvc-cip-auth:1104
            - name: Hierarchy
              value: http://srvc-cip-hierarchy:1106

            - name: Clients__Grpc__Protocols
              value: Http1
            - name: Clients__Grpc__Job
              value: http://srvc-cip-job:1102
            - name: Clients__Grpc__Auth
              value: http://srvc-cip-auth:1104
            - name: Clients__Grpc__Hierarchy
              value: http://srvc-cip-hierarchy:1106

            - name: Clients__RabbitMQz__HostName
              value: srvc-cip-rbmq.sba-dev.svc.cluster.local
              # value: srvc-cip-rbmq.default.svc.cluster.local # When no Namespace
            - name: Clients__RabbitMQz__Port
              value: "5672"
            - name: Clients__RabbitMQz__VirtualHost
              value: /
            - name: Clients__RabbitMQz__Username
              value: guest
            - name: Clients__RabbitMQz__Password
              value: guest
            # - name: Clients__RabbitMQz__Uri
            #   value: amqp://guest:guest@srvc-cip-rbmq.sba-dev.svc.cluster.local/
---
#---------------------------------------------# 
#### (2) API Cluster IP (Auth)
# - We need ClusterIP for Inter Service Communication
# - Production Required
# kubectl port-forward svc/srvc-cip-auth 1104:1104 -n sba-dev
# http://srvc-cip-auth:1104/api/Auth/v1/swagger/index.html
# http://srvc-cip-auth:1104/api/Auth/v1/_projectz-lookup/gets-lookup
---
apiVersion: v1
kind: Service
metadata:
  name: srvc-cip-auth
spec:
  type: ClusterIP
  selector:
    app: srvc-auth
  ports:
  - name: http            # Port for Inter Srvc Comm over Http
    protocol: TCP
    port: 1104
    targetPort: 1104

---
#---------------------------------------------#
#### (3) API Node Port (Auth)
# - We need NodePort for External Service Access
# - No Production Required
apiVersion: v1
kind: Service
metadata:
  name: srvc-np-auth
spec:
  type: NodePort
  selector:
    app: srvc-auth
  ports:
    - name: http
      protocol: TCP
      port: 1104            # ClusterIP service port (internal service port)
      targetPort: 1104      # Pod's container port
      nodePort: 31104       # External NodePort (must be 30000–32767)

## ROUTES (K8S Node Port)
# - http://localhost:31104/api/Auth/v1/swagger/index.html
# - http://localhost:31104/api/Auth/v1/_projectz-lookup/gets-lookup
# - http://localhost:31104/api/Auth/v1/protos/base.proto
# - http://localhost:31104/api/Auth/v1/protos/projectzlookup.proto