################~~~~ SBA APIGateway ~~~~~##################
# - Deployment
# - ClusterIP
# - Node Port

## BASH BUILD Dockerfile
## -t tagname, -f file/reference, ./buildContext  
# docker build -t mansanhhub/srvc-gateway -f Projects/SBA.APIGateway/Dockerfile .
# docker push mansanhhub/srvc-gateway
# docker pull mansanhhub/srvc-gateway

#---------------------------------------------# 
## BASH RUN Deployment srvc-gateway
# kubectl apply -f ./__/K8S/DEV/C_SRVC/depl-gateway.yaml -n sba-dev
# kubectl get pods -n sba-dev
# kubectl get deployments -n sba-dev
# kubectl logs -l app=srvc-gateway --all-containers=true --tail=-1 -n sba-dev
# kubectl rollout restart deployments depl-gateway -n sba-dev

## BASH DELETE (Deployments & Service)8
# kubectl scale deployment depl-gateway --replicas=0 -n sba-dev
# kubectl delete -f ./__/K8S/DEV/C_SRVC/depl-gateway.yaml -n sba-dev
# kubectl delete deployments depl-gateway -n sba-dev
# kubectl delete services srvc-cip-gateway -n sba-dev
#---------------------------------------------# 
#### (1) API Deployment (APIGateway)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srvc-gateway
  template:
    metadata:
      labels:
        app: srvc-gateway
    spec:
      enableServiceLinks: false   # ✅ disables auto-injected env vars
      containers:
        - name: srvc-gateway
          image: mansanhhub/srvc-gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 1100
          env:
            - name: DOTNET_ENVIRONMENT
              value: K8S
            - name: Kestrel__Endpoints__Http__Url
              value: "http://+:1100"
            - name: Kestrel__Endpoints__Http__Protocols
              value: "Http1"
            - name: Kestrel__Endpoints__Https__Url
              value: "https://+:1101"
            - name: Kestrel__Endpoints__Https__Protocols
              value: "Http2"
            - name: Kestrel__Endpoints__Https__Certificate__Path
              value: "dev-cert.pfx"
            - name: Kestrel__Endpoints__Https__Certificate__Password
              value: "yourpassword"

            - name: OcelotFileName
              value: ocelot.K8S.json

---
#---------------------------------------------# 
#### (2) API Cluster IP (APIGateway)
# - We need ClusterIP for Inter Service Communication
# - Production Required
# kubectl port-forward svc/srvc-cip-gateway 1100:1100 -n sba-dev
# http://localhost:1100/api/Gateway/v1/swagger/index.html
# http://localhost:1100/api/Hierarchy/v1/_projectz-lookup/gets-lookup

apiVersion: v1
kind: Service
metadata:
  name: srvc-cip-gateway
spec:
  type: ClusterIP
  selector:
    app: srvc-gateway
  ports:
  - name: srvc-gateway
    protocol: TCP
    port: 1100
    targetPort: 1100
    # nodePort: Not a Valid Option for Cluster IP

---
#---------------------------------------------#
#### (3) API Node Port (APIGateway)
# - We need NodePort for External Service Access
# - No Production Required
apiVersion: v1
kind: Service
metadata:
  name: srvc-np-gateway
spec:
  type: NodePort
  selector:
    app: srvc-gateway
  ports:
    - name: srvc-gateway
      protocol: TCP
      port: 1100 # Node Port
      targetPort: 1100 # Pod's App port
      nodePort: 31100 # 30000-32767 (Host Port)

## ROUTES (K8S Node Port)
# - http://localhost:1100/api/Gateway/v1/swagger/index.html
# - http://localhost:31100/api/Gateway/v1/swagger/index.html