################~~~~ SBA JOB ~~~~~##################
# - Deployment
# - ClusterIP
# - Node Port

## BASH BUILD Dockerfile srvc-job
## -t tagname, -f file/reference, ./buildContext  
# docker system prune
# docker build -t mansanhhub/srvc-job -f Projects/SBA.Job/Dockerfile .
# kubectl get nodes -o wide
# docker push mansanhhub/srvc-job
# docker pull mansanhhub/srvc-job

#---------------------------------------------# 
## BASH RUN Deployment srvc-job
# kubectl apply -f ./__/K8S/DEV/C_SRVC/depl-job.yaml -n sba-dev
# kubectl get pods -n sba-dev
# kubectl get deployments -n sba-dev
# kubectl logs -l app=srvc-job --all-containers=true --tail=-1 -n sba-dev
# kubectl rollout restart deployments depl-job -n sba-dev

## BASH DELETE (Deployments & Service)
# kubectl scale deployment depl-job --replicas=0 -n sba-dev
# kubectl delete -f ./__/K8S/DEV/C_SRVC/depl-job.yaml -n sba-dev
# kubectl delete deployments depl-job -n sba-dev
# kubectl delete services srvc-cip-job -n sba-dev
#---------------------------------------------# 
#### (1) API Deployment (Job) 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srvc-job
  template:
    metadata:
      labels:
        app: srvc-job
    spec:
      enableServiceLinks: false   # ✅ disables auto-injected env vars
      containers:
        - name: srvc-job
          image: mansanhhub/srvc-job
          imagePullPolicy: Always
          ports:
            - containerPort: 1102
          env:
            - name: DOTNET_ENVIRONMENT
              value: K8S
            - name: Kestrel__Endpoints__Http__Url
              value: "http://+:1102"
            - name: Kestrel__Endpoints__Http__Protocols
              value: "Http1"
            - name: Kestrel__Endpoints__Https__Url
              value: "https://+:1103"
            - name: Kestrel__Endpoints__Https__Protocols
              value: "Http2"
            - name: Kestrel__Endpoints__Https__Certificate__Path
              value: "dev-cert.pfx"
            - name: Kestrel__Endpoints__Https__Certificate__Password
              value: "P@ssw0rd!123"

            - name: ConnectionStrings__Redis
              value: "srvc-cip-redis:6379,password=P@55w0rd!123"
            - name: ConnectionStrings__SqlConnection
              value: "Server=srvc-cip-mssql.sba-dev.svc.cluster.local,1433;Initial Catalog=SBA_Job;User ID=sa;Password=P@55w0rd!123;TrustServerCertificate=true;"
            - name: ConnectionStrings__SqlConnectionHangfire
              value: "Server=srvc-cip-mssql.sba-dev.svc.cluster.local,1433;Initial Catalog=SBA_Job_Hangfire;User ID=sa;Password=P@55w0rd!123;TrustServerCertificate=true;"
            - name: ConnectionStrings__SQLite
              value: "Job.SQLite.db"

            - name: Clients__Httpz__Gateway
              value: http://srvc-cip-gateway:1100
            - name: Clients__Httpz__Auth
              value: http://srvc-cip-auth:1104

            - name: Clients__Grpc__Protocols
              value: Http1
            - name: Clients__Grpc__Job
              value: http://srvc-cip-job:1102
            - name: Clients__Grpc__Auth
              value: http://srvc-cip-auth:1104
            - name: Clients__Grpc__Hierarchy
              value: http://srvc-cip-hierarchy:1106

            - name: Clients__RabbitMQz__HostName
              value: srvc-cip-rbmq.sba-dev.svc.cluster.local
            - name: Clients__RabbitMQz__Port
              value: "5672"
            - name: Clients__RabbitMQz__VirtualHost
              value: /
            - name: Clients__RabbitMQz__Username
              value: admin
            - name: Clients__RabbitMQz__Password
              value: admin123

            - name: Hangfire__Title
              value: "Hangfire SBA App"
            - name: Hangfire__Note
              value: "Its a List But required only one"
            - name: Hangfire__Users__0__User
              value: "guest"
            - name: Hangfire__Users__0__Pass
              value: "guest"

---
#---------------------------------------------# 
#### (2) API Cluster IP (Job)
# - We need ClusterIP for Inter Service Communication
# - Production Required
# kubectl port-forward svc/srvc-cip-job 1102:1102
# http://srvc-cip-job:1102/api/job/v1/swagger/index.html
# http://srvc-cip-job:1102/api/job/v1/_projectz-lookup/gets-lookup
# http://srvc-cip-job:1102/api/job/v1/hangfire

apiVersion: v1
kind: Service
metadata:
  name: srvc-cip-job
spec:
  type: ClusterIP
  selector:
    app: srvc-job
  ports:
  - name: srvc-job
    protocol: TCP
    port: 1102
    targetPort: 1102
    # nodePort: Not a Valid Option for Cluster IP

---
#---------------------------------------------#
#### (3) API Node Port (Job)
# - We need NodePort for External Service Access
# - No Production Required
apiVersion: v1
kind: Service
metadata:
  name: srvc-np-job
spec:
  type: NodePort
  selector:
    app: srvc-job
  ports:
    - name: srvc-job
      protocol: TCP
      port: 1102 # Node Port
      targetPort: 1102 # Pod's App port
      nodePort: 31102 # 30000-32767 (Host Port)

## ROUTES (K8S Node Port)
# - http://localhost:31102/api/Job/v1/swagger/index.html
# - http://localhost:31102/api/Job/v1/_projectz-lookup/gets-lookup
# - http://localhost:31102/api/Job/v1/hangfire