################~~~~ Rabbit MQ SBA ~~~~~##################
#### Run Command
## BASH
# kubectl create namespace sba-dev

# kubectl apply -f ./__/K8S/DEV/B_Broker/sfs-rbmq.yaml -n sba-dev
# kubectl get pods -n sba-dev
# kubectl get StatefulSet -n sba-dev
# kubectl delete -f ./__/K8S/DEV/B_Broker/sfs-rbmq.yaml -n sba-dev
# kubectl rollout restart statefulsets sfs-rbmq -n sba-dev

# kubectl logs sfs-rbmq-0 -n sba-dev
# kubectl exec -it sfs-rbmq-0 -n sba-dev -- rabbitmqctl list_vhosts
# kubectl describe pod sfs-rbmq-0 -n sba-dev

## Adding VHost to RabbitMQ
# kubectl exec -it deploy/sfs-rbmq -- rabbitmqctl add_vhost /sba -n sba-dev
# kubectl exec -it deploy/sfs-rbmq -- rabbitmqctl set_permissions -p /sba admin ".*" ".*" ".*" -n sba-dev


#---------------------------------------------#
# (0) RabbitMQ Virtual Host (vhost)
# - kubectl get configmaps -n sba-dev
# - kubectl get configmaps cm-def-rabbit -n sba-dev
# - kubectl delete configmaps cm-def-rabbit -n sba-dev
# - kubectl describe configmap cm-def-rabbit -n sba-dev
# - kubectl get configmap cm-def-rabbit -n sba-dev -o yaml 
#---------------------------------------------#
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: cm-def-rabbit
# data:
#   definitions.json: |
#     {
#       "vhosts": [
#         { "name": "/sba" }
#       ],
#       "permissions": [
#         {
#           "user": "admin",
#           "vhost": "/sba",
#           "configure": ".*",
#           "write": ".*",
#           "read": ".*"
#         }
#       ]
#     }
# ---

#### (3) RabbitMQ Claim (Dev) 

#---------------------------------------------#
# - This Task Done Only Once
# - Creating Claim for Database
# kubectl get pvc -n sba-dev
# kubectl get pvc claim-rbmq -n sba-dev
# kubectl delete pvc claim-rbmq -n sba-dev
#---------------------------------------------#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-rbmq
  namespace: sba-dev
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
  - ReadWriteMany
---

#---------------------------------------------#
# (1) RabbitMQ StatefulSet (SBA)
# - kubectl get statefulset -n sba-dev
# - kubectl get statefulset sfs-rbmq -n sba-dev
# - docker exec -it contID rabbitmqctl list_users -n sba-dev # aec4
# - docker exec -it aec4 rabbitmqctl list_vhosts -n sba-dev
# - kubectl delete statefulset sfs-rbmq -n sba-dev
#---------------------------------------------#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sfs-rbmq
  namespace: sba-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbmq
  template:
    metadata:
      labels:
        app: rbmq
    spec:
      enableServiceLinks: false   # ✅ disables auto-injected env vars
      containers:
        - name: rbmq
          image: rabbitmq:3-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: guest
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
            - name: RABBITMQ_LOAD_DEFINITIONS
              value: /etc/rabbitmq/definitions.json
          ports:
            - name: management
              containerPort: 15672
              protocol: TCP
            - name: amqp
              containerPort: 5672
              protocol: TCP
          volumeMounts:
            - name: rbmq-data
              mountPath: /var/lib/rabbitmq   # ✅ correct RabbitMQ data dir
              
      volumes:
        - name: rbmq-data
          persistentVolumeClaim:
            claimName: claim-rbmq
---
#---------------------------------------------#
# (2) RabbitMQ ClusterIP Service (for internal)
# - Production Required
# - kubectl get svc -n sba-dev
# - kubectl get svc srvc-cip-rbmq -n sba-dev
#---------------------------------------------#

apiVersion: v1
kind: Service
metadata:
  name: srvc-cip-rbmq
  namespace: sba-dev
spec:
  type: ClusterIP
  selector:
    app: rbmq
  ports:
    - name: management
      port: 15672
      targetPort: 15672
      protocol: TCP
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
---
#---------------------------------------------#
#### (5) DB NodePort (Dev) (Optional)
# - We need NodePort for (PC) External Service Access
# - No Production Required
# - kubectl get svc srvc-np-rbmq -n sba-dev
# - CREADENTIALS localhost:32200 sa 'P@55w0rd!123'
#---------------------------------------------#
apiVersion: v1
kind: Service
metadata:
  name: srvc-np-rbmq
  namespace: sba-dev
spec:
  type: NodePort
  selector:
    app: rbmq
  ports:
    - protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 32200 # 30000-32767 (Host Port)

---
#---------------------------------------------#
# (3) RabbitMQ LoadBalancer Service (external)
# - Production Required
# - kubectl get svc -n sba-dev
# - kubectl get svc srvc-lb-rbmq -n sba-dev
# - http://localhost:15670/#/exchanges
#---------------------------------------------#
apiVersion: v1
kind: Service
metadata:
  name: srvc-lb-rbmq
  namespace: sba-dev
spec:
  type: LoadBalancer
  selector:
    app: rbmq
  ports:
    - name: management
      port: 15670 # External Port
      targetPort: 15672
      protocol: TCP
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
