################~~~~ Redis SBA Hierarchy ~~~~~##################
#### Run Command
## BASH
# kubectl apply -f ./__/K8S/DEV/A_DEPL_DB/sfs-redis.yaml -n sba-dev
# kubectl delete -f ./__/K8S/DEV/A_DEPL_DB/sfs-redis.yaml -n sba-dev
# kubectl rollout restart statefulsets sfs-redis -n sba-dev

# kubectl logs sfs-redis-0 -n sba-dev
# kubectl exec -it sfs-redis-0 -n sba-dev -- rabbitmqctl list_vhosts
# kubectl describe pod sfs-redis-0 -n sba-dev

# kubectl port-forward svc/srvc-cip-redis 6379:6379
# ps aux | grep kubectl

## Connect
# redis-cli -h 127.0.0.1 -p 6379 -a 'P@55w0rd!123'
# Node Port 127.0.0.1,32100 sa 'P@55w0rd!123'

#### (3) Redis Claim (Hierarchy) 

# - This Task Done Only Once
# - Creating Claim for Redis
# kubectl get pvc -n sba-dev
# kubectl get pvc claim-redis -n sba-dev
# kubectl delete pvc claim-redis -n sba-dev
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-redis
  namespace: sba-dev
spec:
  storageClassName: hostpath
  resources:
    requests:
      storage: 500Mi
  accessModes:
  - ReadWriteOnce

---

#### (3) Redis StatefulSet (Hierarchy) 
# - kubectl get statefulset -n sba-dev
# - kubectl get statefulset sfs-redis -n sba-dev
# - kubectl delete statefulset sfs-redis -n sba-dev
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sfs-redis
  namespace: sba-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      enableServiceLinks: false   # ✅ disables auto-injected env vars
      containers:
        - name: redis
          image: redis:latest
          args: ["redis-server", "--requirepass", "P@55w0rd!123"]
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: 512Mi
              cpu: "500m"
            requests:
              memory: 256Mi
              cpu: "250m"
          volumeMounts:
            - mountPath: /data
              name: redisdb
      volumes:
        - name: redisdb
          persistentVolumeClaim:
            claimName: claim-redis

---

#---------------------------------------------# 
#### (4) Redis ClusterIP (Hierarchy)
# - We need ClusterIP for Inter Service Communication
# - Production Required
# - kubectl get svc -n sba-dev
# - kubectl get svc srvc-cip-redis -n sba-dev
apiVersion: v1
kind: Service
metadata:
  name: srvc-cip-redis
  namespace: sba-dev
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379 # Port -> Cluster 
      targetPort: 6379 # Port -> (Pod / Container)

---
#---------------------------------------------#
#### (5) Redis NodePort (Dev)
# - We need NodePort for (PC) External Service Access
# - No Production Required
# - kubectl get svc srvc-np-redis -n sba-dev
# - CREADENTIALS 127.0.0.1,32100 sa 'P@55w0rd!123'
apiVersion: v1
kind: Service
metadata:
  name: srvc-np-redis
  namespace: sba-dev
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 32100 # 30000-32767 (Host Port)

---
#---------------------------------------------#
#### (6) Redis LoadBalancer (Dev)
# - We need LoadBalancer for (Public) External Service Access
# - No Production Required
# - kubectl get svc srvc-lb-redis -n sba-dev
## Credentials for LoadBalancer
# - 127.0.0.1,6379 'P@55w0rd!123'
apiVersion: v1
kind: Service
metadata:
  name: srvc-lb-redis
  namespace: sba-dev
spec:
  type: LoadBalancer
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
