################~~~~ SBA HIERARCHY ~~~~~##################
# - Deployment
# - ClusterIP
# - Node Port

## BASH BUILD Dockerfile srvc-hierarchy
## -t tagname, -f file/reference, ./buildContext  
# docker build -t mansanhhub/srvc-hierarchy -f Projects/SBA.Hierarchy/Dockerfile .
# docker push mansanhhub/srvc-hierarchy
# docker pull mansanhhub/srvc-hierarchy

#---------------------------------------------# 
## BASH RUN Deployment srvc-hierarchy
# kubectl apply -f ./__/K8S/DEV/B_DEPL_SRVC/depl-hierarchy.yaml -n sba-dev
# kubectl get pods -n sba-dev
# kubectl get deployments -n sba-dev -n sba-dev
# kubectl logs -l app=srvc-hierarchy -n sba-dev
# kubectl logs -l app=srvc-hierarchy --all-containers=true --tail=-1 -n sba-dev
# kubectl logs -l app=srvc-hierarchy -f --all-containers=true -n sba-dev
# kubectl rollout restart deployments depl-hierarchy -n sba-dev

## BASH DELETE (Deployments & Service)
# kubectl scale deployment depl-hierarchy --replicas=0 -n sba-dev
# kubectl delete -f ./__/K8S/DEV/B_DEPL_SRVC/depl-hierarchy.yaml -n sba-dev
# kubectl delete deployments depl-hierarchy -n sba-dev
# kubectl delete services srvc-cip-hierarchy -n sba-dev
#---------------------------------------------# 
#### (1) API Deployment (Hierarchy) 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-hierarchy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srvc-hierarchy
  template:
    metadata:
      labels:
        app: srvc-hierarchy
    spec:
      enableServiceLinks: false   # ✅ disables auto-injected env vars
      containers:
        - name: srvc-hierarchy
          image: mansanhhub/srvc-hierarchy
          imagePullPolicy: Always
          ports:
            - containerPort: 1106
          env:
            - name: DOTNET_ENVIRONMENT
              value: K8S
            - name: ASPNETCORE_URLS
              value: http://+:1106

            - name: ConnectionStrings__Redis
              value: "srvc-cip-redis-dev:6379,password=P@55w0rd!123"
            - name: ConnectionStrings__SqlConnection
              value: "Server=srvc-cip-mssql-dev.default.svc.cluster.local,1433;Initial Catalog=SBA_Hierarchy;User ID=sa;Password=P@55w0rd!123;TrustServerCertificate=true;"
              # value: "Server=srvc-cip-mssql-hierarchy.default.svc.cluster.local,1433;Initial Catalog=SBA_Hierarchy;User ID=sa;Password=P@55w0rd!123;TrustServerCertificate=true;"
            
            - name: Clients__Http_Host__Gateway
              value: http://srvc-cip-gateway:1100
            - name: Clients__Http_Host__Auth
              value: http://srvc-cip-auth:1104

            - name: Clients__Grpc__Protocols
              value: Http1
            - name: Clients__Grpc__Job
              value: http://srvc-cip-job:1102
            - name: Clients__Grpc__Auth
              value: http://srvc-cip-auth:1104
            - name: Clients__Grpc__Hierarchy
              value: http://srvc-cip-hierarchy:1106

            - name: Clients__RabbitMQz__HostName
              value: srvc-cip-rbmq.default.svc.cluster.local
            - name: Clients__RabbitMQz__Port
              value: "5672"
            - name: Clients__RabbitMQz__VirtualHost
              value: /
            - name: Clients__RabbitMQz__Username
              value: guest
            - name: Clients__RabbitMQz__Password
              value: guest
            # - name: Clients__RabbitMQz__Uri
            #   value: amqp://guest:guest@srvc-cip-rbmq.default.svc.cluster.local/
---
#---------------------------------------------# 
#### (2) API Cluster IP (Hierarchy)
# - We need ClusterIP for Inter Service Communication
# - Production Required
# kubectl port-forward svc/srvc-cip-hierarchy 1106:1106 -n sba-dev
# http://srvc-cip-hierarchy:1106/api/hierarchy/v1/swagger/index.html
# http://srvc-cip-hierarchy:1106/api/hierarchy/v1/_projectz-lookup/gets-lookup

apiVersion: v1
kind: Service
metadata:
  name: srvc-cip-hierarchy
spec:
  type: ClusterIP
  selector:
    app: srvc-hierarchy
  ports:
  - name: srvc-hierarchy
    protocol: TCP
    port: 1106
    targetPort: 1106
    # nodePort: Not a Valid Option for Cluster IP

---
#---------------------------------------------#
#### (3) API Node Port (Hierarchy)
# - We need NodePort for External Service Access
# - No Production Required
apiVersion: v1
kind: Service
metadata:
  name: srvc-np-hierarchy
spec:
  type: NodePort
  selector:
    app: srvc-hierarchy
  ports:
    - name: srvc-hierarchy
      protocol: TCP
      port: 1106 # Node Port
      targetPort: 1106 # Pod's App port
      nodePort: 31106 # 30000-32767 (Host Port)

## ROUTES (K8S Node Port)
# - http://localhost:31106/api/Hierarchy/v1/swagger/index.html
# - http://localhost:31106/api/hierarchy/v1/_projectz-lookup/gets-lookup