syntax = "proto3";

option csharp_namespace = "SBA.Projectz.Grpc.Model";

package sba.projectz.grpc;

import "base.proto";

service GrpcProjectzLookup {
  rpc Gets (BaseGrpcGets) returns (BaseGrpcProjectzLookups) {
    // option (google.api.http) = {
    //   get: "/v1/todos"
    // };
  }

  rpc Get (BaseGrpcById) returns (BaseGrpcProjectzLookup) {
    // option (google.api.http) = {
    //   get: "/v1/todo"
    // };
  }

  rpc Create (BaseGrpcCreate) returns (BaseGrpcRes) {
    // option (google.api.http) = {
    //   post: "/v1/todo"
    // };
  }

  rpc Update (BaseGrpcUpdate) returns (BaseGrpcRes) {
    // option (google.api.http) = {
    //   put: "/v1/todo"
    // };
  }

  rpc UpdateStatus (BaseGrpcById) returns (BaseGrpcRes) {
    // option (google.api.http) = {
    //   patch: "/v1/todo"
    // };
  }

  rpc Delete (BaseGrpcById) returns (BaseGrpcRes) {
    // option (google.api.http) = {
    //   delete: "/v1/todo"
    // };
  }
}
