version: '3.9'
services:
  hierarchy:
    image: mansanhhub/srvc-hierarchy
    container_name: srvc-hierarchy
    environment:
      - DOTNET_ENVIRONMENT=Docker
    networks:
      - sba-dev-network
    ports:
      - "1106:1106"
      - "1107:1107"
    volumes:
      - //c/D/net-micro/dev-cert.pfx:/app/dev-cert.pfx:ro

networks:
  sba-dev-network:
    external: true

# ### Docker Compose CLI
# docker-compose up -d --build
# docker-compose down

# ### ROUTE (Docker Port Mapping)
# - http://localhost:1106/api/hierarchy/v1/swagger/index.html
# - http://localhost:1106/api/hierarchy/v1/_projectz-lookup/gets-lookup
